services:
  # php
  php:
    container_name: php_container
    restart: always
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup_network

  # nginx
  nginx:
    container_name: nginx_container
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '8585:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup_network

  # pgsql
  pgsql:
    container_name: pgsql_container
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - setup_network

  # pgadmin4
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:9
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    depends_on:
      - pgsql
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - setup_network

volumes:
  pgdata:
  pgadmin_data:

networks:
  setup_network:
    driver: bridge